apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: auto-demo
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: exam-app
    spec:
      containers:
      - name: exam-app-container
        image: colornokia/k8s-exam-app:latest
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: exam-app-svc
  labels:
    app: exam-app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: exam-app
