apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpfpm-host
spec:
  selector:
    matchLabels:
      app: phpfpm
  replicas: 1
  template:
    metadata:
      labels:
        app: phpfpm
    spec:
      containers:
      - name: phpfpm
        image: colornokia/phpfpm:latest
        ports:
        - containerPort: 9000
        ---
apiVersion: v1
kind: Service
metadata:
  name: phpfpm-svc
  labels:
    app: phpfpm
spec:
  type: NodePort
  ports:
  - port: 9000
    nodePort: 32000
    protocol: TCP
  selector:
    app: phpfpm
